module.exports = {
  NOTIFICATION_REMOVE: 'NOTIFICATION_REMOVE',
  NOTIFICATION_ADD: 'NOTIFICATION_ADD',

  COMMAND_REMOVE: 'COMMAND_REMOVE',
  COMMAND_ADD: 'COMMAND_ADD',

  LOAD_FROM_LOCAL_STORAGE: 'LOAD_FROM_LOCAL_STORAGE',
};
